index:
    path:     /
    defaults: { _controller: AppBundle:Person:index }

person_show:
    path:     /show/{id}
    defaults: { _controller: AppBundle:Person:show }

person_create:
    path:     /create
    defaults: { _controller: AppBundle:Person:create }

person_update:
    path:     /update
    defaults: { _controller: AppBundle:Person:update }

person_delete:
    path:     /delete
    defaults: { _controller: AppBundle:Person:delete }
