AppBundle\Entity\Person:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            column: first_name
        lastName:
            type: string
            length: 255
            column: last_name
        address:
            type: text
            nullable: true
        zip:
            type: string
            length: 255
        city:
            type: string
            length: 255
        country:
            type: string
            length: 255
        phoneNumber:
            type: string
            length: 255
            column: phone_number
        birthday:
            type: date
        email:
            type: string
            length: 255
            unique: true
        picture:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
